
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```

```{r}
set.seed(123)
file_prep <- function(states, ratio, years) {
  for (st in states){
    for (yr in years){
      yrr = yr + 2000
      url <- paste("https://www2.census.gov/programs-surveys/acs/data/pums/",yrr, "/1-Year/csv_p",st,".zip", sep = "")
      file_name <- paste("csv_p",st,".zip", sep = "")
      file_path <- "~/Honors-thesis-code/unzip_data/"
      download.file(url, paste(file_path, file_name, sep = ""))
      
      unzip(paste(file_path, file_name, sep = ""), list = FALSE, 
        overwrite = TRUE,
      junkpaths = FALSE, exdir = "~/Honors-thesis-code/unzip_data/", unzip = "internal",
      setTimes = FALSE)
      csv_files = list.files("~/Honors-thesis-code/unzip_data/", pattern = "\\.csv$", full.names = T)
      csv_file = csv_files[1]
      singledf = read_csv(csv_file, col_types = cols(AGEP = "d", SEMP = "d" ))
      if (ratio != 1){
        singledf = singledf %>%
          filter(
            AGEP >= 20,
            AGEP <= 50,
            SEX == 2
          )
        singledf = singledf %>%
          sample_n(nrow(singledf)*ratio) %>%
          mutate(YEAR = yr + 2000, STATE = st)
      }
      else {
        singledf = singledf %>%
          filter(
            AGEP >= 20,
            AGEP <= 50,
            SEX == 2) %>%
          mutate(YEAR = yr + 2000, STATE = st)
      }
      write.table(singledf, file = paste("~/Honors-thesis-code/processed_data/",st,yr,".csv", sep = ""), sep = ",", row.names = F)
        
        
      
      
      file.remove(csv_file)
    }
  }
}

create_df <- function(states){
  csv_files <- list.files("~/Honors-thesis-code/processed_data/", full.names = F)
  pattern <- paste0("^(", paste(states, collapse = "|"), ")")
  csv_files <- csv_files[grep(pattern, csv_files)]
  csv_files <- paste0("~/Honors-thesis-code/processed_data/", csv_files)
  
  column_spec <- cols_only(
    STATE = col_character(),
    AGEP = col_double(),
    FER = col_double(),
    SEX = col_double(),
    YEAR = col_double(),
    PAOC = col_double(),
    PINCP = col_double(),
    PWGTP = col_double())
  
  fulldf <- map_df(csv_files, ~ read_csv(.x, col_types = column_spec))
  
  fulldf <- fulldf %>%
    mutate(PINCP = ifelse(PINCP < 1, 1, PINCP))%>%
    mutate(LOGINC = log(PINCP), AGESQ = AGEP^2) %>%
    filter(STATE != "STATE") %>%
  return(fulldf)
}
```


Manipulating the following code chunk to choose the specifications of 
the dataframe.
```{r}
setwd("~/Honors-thesis-code/")


#Add and remove acronyms from state_list to manipulate what states get saved
#into the data frame. ratio_v chooses the relative size of the dataframe saved
#compared to the size of the full dataframe. So a ratio_v = 0.5 will remove half
#the data. With a small amount of states its fine to use ratio_v = 1.
years = seq(7, 22)
years = years[years != 20]
state_list = c("co", "wa", "or")
ratio_v = 1
file_prep(state_list, ratio_v, years)
df_did <- create_df(state_list)

```

