The following chunks create event study plots for each place where the policy
was implemented




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fastDummies)
library(ggplot2)
library(tidyverse)
library(plm) #panel linear model
library(lfe) #linear fixed effect model
library(fixest)
```

```{r}
#Set up dataframe for difference in difference estimation and event study plot
df = df_did %>%
  filter(STATE == "wa" | STATE == "co"| STATE == "or") %>%
  mutate(eligible = ifelse(STATE == "wa", 1, 0)) %>%
  mutate(PFML = ifelse(YEAR >= 2021, 1, 0)) %>%
  mutate(interact = eligible * YEAR) %>%
  mutate(FER = ifelse(FER == "2", 0, 1))


#difference in difference with covariates

model <- lm(FER~STATE + PFML + interact + AGEP + AGESQ + LOGINC, data = df)
sink("~/Honors-thesis-code/visualizations/DiDWAsummary.txt")
summary(model)
sink()




#two way fixed effects omitting 2019 as base year

model <- feols(FER~i(YEAR,eligible,2019)|STATE + YEAR, data = df)
pdf("WAeventstudyplot.pdf")
coefplot(model, xlab = "2019 as base year. 2020 data unavailable due to covid", main = "Washington event study (OR, CO as controls)")
dev.off()
file.rename(from = "~/Honors-thesis-code/code/WAeventstudyplot.pdf", to = "~/Honors-thesis-code/visualizations/WAeventstudyplot.pdf")





#fertility rate graphed by state
fergraph <- df %>%
  group_by(STATE, YEAR) %>%
  summarize(avg = mean(FER))

fer_df <- df %>%
  group_by(STATE, YEAR, AGEP, FER) %>%
  mutate(
    num_people_by_age_fer = sum(PWGTP)
  ) %>%
  ungroup() %>%
  group_by(STATE, YEAR, AGEP) %>%
  mutate(
    age_fer_ratio = num_people_by_age_fer / sum(PWGTP)
  ) %>%
  ungroup() %>%
  filter(FER == 1) %>%
  select(STATE, YEAR, AGEP, age_fer_ratio) %>%
  unique() %>%
  group_by(STATE, YEAR) %>%
  mutate(
    tfr = sum(age_fer_ratio)
  ) %>%
  select(STATE, YEAR, tfr) %>%
  unique() %>%
  filter(!is.na(tfr))

fergraph <- df %>%
  group_by()
number_ticks <- function(n) {function(limits) pretty(limits, n)}

ggplot(data=fer_df, aes(x=YEAR, y=tfr, group = STATE, color = STATE)) +
  geom_line() +
  ylab("odds of child within 12 months") +
  coord_cartesian(ylim = c(1, 3)) +
  scale_x_continuous(breaks=number_ticks(15)) +
  ggtitle("Fertility rates")


ggsave("~/Honors-thesis-code/visualizations/WAORCOfertilitygraph.pdf")
```